drop table holidays if exists
drop table employee if exists
create table employee (id bigint generated by default as identity (start with 1), f1 char, f2 char, f3 char, f4 char, l1 char, l2 char, l3 char, l4 char, office varchar(255), primary key (id))
create table holidays (id bigint generated by default as identity (start with 1), end_date timestamp not null, start_date timestamp not null, employee_id bigint, primary key (id))
alter table holidays add constraint FK_5ugk8oth3d4r3fon7jcuksiow foreign key (employee_id) references employee
